import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { auth } from "@/auth";
import { redirect } from "next/navigation";

import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import Link from "next/link";
import Notifications from "@/components/navbar/notifications";
import Sidebar from "@/components/sidebar/primary-sidebar";
import MobileSidebar from "@/components/sidebar/secondary-sidebar";
import SearchBar from "@/components/header/searchbar";
import UserButton from "@/components/header/user-button";

import TanstackProvider from "@/components/providers/tanstack-provider";
import { ModeToggle } from "@/components/navbar/mode-toggle";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
//   let user;
//   try {
//     const session = await auth();
//     user = session?.user;
//   } catch (error) {
//     console.error("Failed to fetch user session:", error);
//     redirect("/error");
//     return null;
//   }

//   if (!user) {
//     redirect("/login");
//     return null;
//   }

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <div className="grid min-h-screen w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr]">
            <div className="hidden border-r bg-muted/40 md:block">
              <div className="flex h-full max-h-screen flex-col gap-2">
                <div className="flex h-14 items-center border-b px-4 lg:h-[60px] lg:px-6">
                  <Link href="/" className="flex items-center gap-2 font-semibold">
                    <span className="text-muted-foreground text-2xl font-semibold">
                      HEEGA
                    </span>
                  </Link>
                </div>
                <Sidebar />
              </div>
            </div>
            <div className="flex flex-col">
              <header className="flex h-14 items-center gap-4 border-b bg-muted/40 px-4 lg:h-[60px] lg:px-6">
                <MobileSidebar />
                <div className="w-full flex-1">
                  <SearchBar />
                </div>
                <ModeToggle />
                <Notifications />
                <UserButton />
              </header>
              <TanstackProvider>{children}</TanstackProvider>
            </div>
          </div>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
